# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: ticsqualitygate@0
  inputs:
    ticsqualitygateapi: 'https://viewer-sdk4ed.tiobe.com/tiobeweb/TICS/api/public/v1/Measure?metrics=tqiCodingStd&filters=Project(SDK4EDIntegration)'
    projectname: 'SDK4EDIntegration'
    projectbranch: 'master'
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonarqube_beza_home'
    scannerMode: 'Other'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'

